workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      android_signing:
        - prixity-keystore.jks
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.prixity.ecommerce.app"
        GOOGLE_PLAY_TRACK: alpha
      flutter: stable
    scripts:
      - name: Decode google-services.json from Base64
        script: |
          # Access environment variable with group name
          BASE64_ENCODED_JSON=${!google_play_GOOGLE_SERVICES_JSON}
          # Decode the Base64 string
          echo "$BASE64_ENCODED_JSON" | base64 --decode > config/android/prod/google-services.json

          # Optional: Verify decoding success (check for empty file)
          if [[ ! -s "config/android/prod/google-services.json" ]]; then
            echo "Error: Decoded google-services.json is empty!"
            exit 1  # This will cause the build to fail
          fi
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: | 
          # BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build apk -t lib/main_prod.dart --flavor prod \
            --keystore-path=./prixity-keystore.jks \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    # publishing:
    #   email:
    #     recipients:
    #       - user_1@example.com
    #       - user_2@example.com
    #     notify:
    #       success: true
    #       failure: false
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: $GOOGLE_PLAY_TRACK
    #     submit_as_draft: true