workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    triggering:
      events:
        - tag
      cancel_previous_builds: true
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.prixity.ecommerce.app"
      flutter: stable
    scripts:
      - name: Setup the keystore
        script: |
          # paste the keystore file in tmpdir
          echo $KEY_STORE_FILE | base64 --decode > /tmp/keystore.jks
          # create a key.properties and store the values in it
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEY_STORE_PASS
          keyPassword=$KEY_STORE_PASS
          keyAlias=$KEY_ALIAS
          storeFile=/tmp/keystore.jks
          EOF
      - name: Create directory structure
        script: |
          mkdir -p config/android/prod
      - name: Decode google-services.json from Base64
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > config/android/prod/google-services.json
      - name: Copy the google-services file to android section
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/src/prod/google-services.json
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Flutter analyze
        script: | 
          flutter analyze
      # - name: Flutter unit tests
      #   script: | 
      #     flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: | 
          # BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle -t lib/main_prod.dart --flavor prod \
            # --keystore-path=./prixity-keystore.jks \
            # --build-name=1.0.$BUILD_NUMBER \
            # --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - kashifumar349@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GOOGLE_CLOUD_SERVICE_ACCOUNT
        track: internal
        submit_as_draft: true